[general]
live_config_reload = true

[terminal.shell]
program = "/bin/zsh"

[window]
decorations = "Buttonless"
startup_mode = "Maximized"
option_as_alt = "Both"

[font]
normal = { family = "CaskaydiaCove Nerd Font", style = "Regular" }
size = 14.0
