add_newline = false

format = """
[](fg:8)\
$os\
$username\
[](fg:8 bg:1)\
$directory\
[](fg:1 bg:2)\
$git_branch\
$git_status\
$git_metrics\
[](fg:2 bg:3)\
$c\
$cmake\
$lua\
$nodejs\
[](fg:3 bg:4)\
$docker_context\
[](fg:4 bg:5)\
$time\
[ ](fg:5)\
$line_break\
$character\
"""

[os]
disabled = false
style = "fg:16 bg:8"

[os.symbols]
Windows = "󰍲"
Macos = ""
Linux = "󰌽"
Arch = "󰣇"

[username]
show_always = true
style_user = "fg:16 bg:8"
format = "[ $user ]($style)"

[directory]
style = "fg:16 bg:1"
format = "[ $path ]($style)"
truncation_length = 2
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
always_show_remote = true
style = "fg:16 bg:2"
format = "[  $branch  $remote_branch ]($style)"

[git_status]
style = "fg:16 bg:2"
format = "[$all_status$ahead_behind ]($style)"

[git_metrics]
disabled = false
added_style = "fg:16 bg:2"
deleted_style = "fg:16 bg:2"
format = "[+$added ]($added_style)[-$deleted ]($deleted_style)"

[c]
symbol = ""
style = "fg:16 bg:3"
format = "[ $symbol $version ]($style)"

[cmake]
symbol = "󰔷"
style = "fg:16 bg:3"
format = "[ $symbol $version ]($style)"

[lua]
symbol = ""
style = "fg:16 bg:3"
format = "[ $symbol $version ]($style)"

[nodejs]
symbol = ""
style = "fg:16 bg:3"
format = "[ $symbol $version ]($style)"

[docker_context]
symbol = ""
style = "fg:16 bg:4"
format = "[ $symbol $context ]($style)"

[time]
disabled = false
time_format = "%T"
style = "fg:16 bg:5"
format = "[  $time ]($style)"

[line_break]
disabled = false

[character]
disabled = false
success_symbol = "[ ](fg:2)"
error_symbol = "[ ](fg:1)"
vimcmd_symbol = "[ N](bold fg:2)"
