[colors]
ansi = [
  '#5c5f77',
  '#d20f39',
  '#40a02b',
  '#df8e1d',
  '#1e66f5',
  '#ea76cb',
  '#179299',
  '#acb0be'
]
brights = [
  '#6c6f85',
  '#d20f39',
  '#40a02b',
  '#df8e1d',
  '#1e66f5',
  '#ea76cb',
  '#179299',
  '#bcc0cc'
]
background = '#eff1f5'
foreground = '#4c4f69'
cursor_bg = '#4c4f69'
cursor_fg = '#4c4f69'
selection_bg = '#4c4f69'
selection_fg = '#4c4f69'

[metadata]
name = 'catppuccin-latte'
