[colors]
ansi = [
  '#45475a',
  '#f38ba8',
  '#a6e3a1',
  '#f9e2af',
  '#89b4fa',
  '#f5c2e7',
  '#94e2d5',
  '#bac2de'
]
background = '#1e1e2e'
brights = [
  '#585b70',
  '#f38ba8',
  '#a6e3a1',
  '#f9e2af',
  '#89b4fa',
  '#f5c2e7',
  '#94e2d5',
  '#a6adc8'
]
cursor_bg = '#cdd6f4'
cursor_fg = '#cdd6f4'
foreground = '#cdd6f4'
selection_bg = '#cdd6f4'
selection_fg = '#cdd6f4'

[colors.indexed]

[metadata]
name = 'catppuccin_mocha'
origin_url = 'https://github.com/Gogh-Co/Gogh/blob/master/themes/Catppuccin%20Mocha.yml'
